source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  use_frameworks!
  platform :ios, '12.0'
  inhibit_all_warnings!

  pod 'RxKingfisher', :path => '../'
  pod 'Fakery'
  pod 'RxCocoa', '>= 6.0.0-rc.1'
end
